var PluginLoader = require('./lib/services/plugin.loader');
var ServiceLoader = require('./lib/services/service.loader');
var RouteLoader = require('./lib/services/route.loader');
var MethodLoader = require('./lib/services/method.loader');
var HandlerLoader = require('./lib/services/handler.loader');
var EventLoader = require('./lib/services/event.loader');
var initialisePlugin = function (config) {
    var pluginLoader = new PluginLoader.default(config);
    var eventLoader = new EventLoader.default();
    var methodLoader = new MethodLoader.default();
    var handlerLoader = new HandlerLoader.default();
    var serviceLoader = new ServiceLoader.default();
    var routeLoader = new RouteLoader.default();
    serviceLoader.setEventLoader(eventLoader);
    serviceLoader.setMethodLoader(methodLoader);
    serviceLoader.setHandlerLoader(handlerLoader);
    pluginLoader.setRouteLoader(routeLoader);
    pluginLoader.setServiceLoader(serviceLoader);
    return pluginLoader;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = initialisePlugin;
